language: node_js
node_js:
  - "11.5.0"
cache:  
  directories:  
    - "node_modules"  
services:  
  - mongodb  
before_script:  
  - cp config/database.ci.js config/database.js  
  - psql -c 'create database mymoney_ci_test;' -U postgres  
script:  
  - npm run lint  
  - npm run test